var palabras = [ //array de palabras para mostrar
    'CSS Grid layout', 'Flexbox', 'Templates strings', 'columns', 'Rows', 'white-space', 'nowrap',
    'transform', 'prototype', 'browser', 'stringify', 'svg', 'parse', 'interpolacion', 'unshift', 'join',
    'push', 'pop', 'every', 'find', 'fill', 'diagramas de flujo', 'polimorfismo', 'encapsulación', 'head',
    'herencia', 'v8', 'dataset', 'mockup', 'foreach', 'semantica', 'vanillajs', 'arrow function', 'tcp/ip',
    'tdd', 'div', 'Elemento en bloque', ':root', 'findIndex', '!', 'arguments', 'livescript', 'mocha',
    'iterador', 'cache', 'localStorage', 'sessionStorage', 'webSql', 'SQL', 'width', 'height', 'umd',
    'pwa', 'amd', 'border', 'collapse', 'fixed', 'relative', 'em', 'rem', 'acoplamiento', 'ddd',
    'fr', 'callback', 'setProperty', 'sintaxis', 'appendChild', 'API', 'Capa de abstracción', 'mouseover',
    'blur', 'onclick', 'keypress', 'keyup', 'keydown', 'toggle', 'RegExp', 'node', 'nodelist', 'HTMLelement',
    'parentNode', 'Métodos', 'type=text', 'type=password', 'checkbox', 'dropdownlist', 'widget', 'type=range',
    'type=number', 'cookies', 'form', 'stopPropagation', 'preventDefault', 'submit', 'post', 'get', 'HTTP request',
    'checkvalidity', 'switch', 'boxsizing', 'break', 'for (atribute)', 'font-family', 'font-size', 'recursividad',
    'functional', 'paradigma', 'patron de diseño ', 'scope', 'modulo', '%', 'dependencia', 'html5', '++',
    '+=', '-=', '*=', '/=', 'Jest', 'slice', 'splice', '"==="', 'concat', 'publish', 'boolish',
    'typeof', 'instanceof', 'objeto literal', 'object', 'propiedades', 'servidor', 'IIS', 'web application', 'web page',
    ' < span>', 'color', 'tag', 'innerText', 'Reverse', 'sort', 'some', 'reduceRight', 'if', 'else',
    'responsive', 'it', 'debug', 'console', 'toEqual', 'breakpoint', 'endPoint', 'promesas', 'fetch', 'then',
    'try', 'finally', '()', '.', '=', '[]', '//', '||', '&&', 'and', 'or', '../', './', '${}', 'replace',
    'ig', 'Programación', 'undefined', 'null', 'NaN', 'infinity', 'multiparadigma', 'stackoverflow', 'codesandbox',
    'mozilla msdn', 'internet explorer', 'chromium', 'xml', 'xmlHTTPrequest', 'XHTML', 'S5.JS', 'Git push', 'pull request',
    'removeItem', 'clear()', 'transaction', 'setInterval', 'setTimeout', 'ClearTimeout', 'ClearInterval', 'Referencia o Valor', 'align-items',
    'Justify-Content', 'body', 'margin', 'ViewPort', 'codigo servidor200 ', 'codigo servidor 404', 'codigo servidor 500', 'syntax error', 'ubuntu',
    'linux', 'windows 10', 'max', 'min', 'edge', 'value', 'content', 'keycode', 'tabkey', 'controlkey', 'altkey',
    'class', '!important', 'z-index', 'this', '</b>', 'commonJS', 'nodeJS', 'asp', 'php', 'jdk', 'sdk',
    'ide', 'isp', 'button', 'title', 'overflow', 'metaTag', 'Internet', 'autoplay', 'red', 'RJ45',
    'currentTime', 'load', 'loop', 'muted', 'application', 'pause', 'paused', 'play', 'src', 'href', 'target',
    'visibility', 'hidden', 'px', 'focus', 'getClientRects', 'main', 'void', 'localhost', 'ip', 'location',
    'setAttribute', '::before', '::after', 'removeAttribute', 'getAttribute', 'id', 'name', 'for attribute', 'querySelectorALL', 'JavaScript ',
    'HiperTexto', 'HiperMedia', 'Concurrencia', 'Asincrono', 'Sincrono', 'CSS', 'Link', 'Script', 'querySelector', 'document',
    'window', 'addEventListener', 'Array', 'filter', 'reduce', 'Variable', 'Heap', 'var', 'let', 'const',
    'string', 'Number', 'Boolean', 'Operador ternario', 'Evento', 'W3C', 'ECMA', 'Lenguaje', 'Dominio', 'Hosting',
    'HTTP', 'GIT', 'Repositorio', 'Front-End', 'Recurso', 'TCP/IP', 'IP', 'DOM', 'Pseudoselector', 'Enlaces', 'ClassList', 'ClassName',
    ';', ':', '`', 'charset', 'UTF8', 'getElementById', '<', '>', '> (css)', 'not (selector)', 'h1', ':hover',
    'cursor:pointer', 'ftp', 'smtp', 'protocolo', 'outline', 'border-radius', '* (operador)', '* (selector)', '<style>', '<br>', '<hr>',
    'webassembly', 'base de datos', 'padding', 'mysql', 'toString', 'SqlLite', 'destructuring', 'iframe', 'Date', 'office', 'outlook',
    'teams', 'daily', 'scrum', 'obj["prop"]', 'funciones puras', 'lambda', 'bootstrap', 'preprocesador', 'sass', 'less', 'foundation',
    'apache', 'onChange', 'required', 'form', 'querySelector([name="x"])', 'alert', 'interpolación', '<li>', 'join', 'localstorage',
    'key value', 'arrow function', 'map', 'snake_case', 'camelCase', 'JSON', 'const', 'algoritmo', 'CTRL + F5', '"+" (selector CSS)', '[object Object]',
    'parseInt', '() ? :', ': checked', 'push()', 'innerHTML', 'localstorage.setItem', 'form.reset()', 'onblur', '<kbd>', 'transitionend',
    'catch()', 'spread operator', 'some()'];